include:
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/Scan/php.yml
  - remote: https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/php_common.yml
  - template: SAST.gitlab-ci.yml
  - file: /license_management.yml
    project: jitesoft/gitlab-ci-lib

stages:
  - test
  - scan

test:
  extends: .php:test:unit

sniff:
  extends: .php:test:sniff
