include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

stages:
  - test
  - scan

build:
  stage: test
  image: jitesoft/composer
  script:
    - composer install --prefer-dist --no-progress
    - vendor/bin/phpunit tests/ --coverage-text --colors=never --whitelist=src/
    - vendor/bin/phpcs -p ./src --report=summary --standard=./style.xml

scan:dep:
  extends: .dependency_scanning

scan:code:
  extends: .code_quality
