include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/dependency_scanning.yml

stages:
  - test
  - scan

test:7.4:
  stage: test
  image: registry.gitlab.com/jitesoft/dockerfiles/phpunit:7.4
  script:
    - composer install --prefer-dist --no-progress
    - composer test

scan:
  extends: .scan:composer
